### ISSUE TITLE
Species `name_usage` params include unsupported parameters

### ISSUE THREAD

**Issue by kspurgin** [sckott/gbifrb#73]
The following params on the Species `name_usage` method are not supported and do not work:

- key
- data
- uuid
- rank
- shortname

These parameters are not listed for this search method on https://www.gbif.org/developer/species

Details on each below, and a PR forthcoming.

**key**

I cannot seem to find any key that has any effect when passed in here. The result set always begins with taxonID=>gbif:0 and seems to include everything.

**data**
I saved the results for:

https://api.gbif.org/v1/species?name=Puma%20concolor

and

https://api.gbif.org/v1/species?name=Puma%20concolor&data=all

The files were identical when diffed.

**uuid**

The comments in the code say this should work the same as datasetKey

```ruby
test = species.name_usage(name: 'Andropogon', datasetKey: '3f8a1297-3259-4700-91fc-acc4170b27ce')
test['results'].length
=> 2
test['results'].each{ |r| puts r['key'] }
100015804
100015805
```

But it does not:

```ruby
test = species.name_usage(name: 'Andropogon', uuid: '3f8a1297-3259-4700-91fc-acc4170b27ce')
test['results'].length
=> 89
test['results'].first['key']
=> 2706077
test['results'].last['key']
=> 181589405
```

It has no effect, and produces the same results as passing only the `name` parameter:

```ruby
test = species.name_usage(name: 'Andropogon')
test['results'].length
=> 89
test['results'].first['key']
=> 2706077
test['results'].last['key']
=> 181589405
```

**rank**

Does not seem to have any effect:

```ruby
test = species.name_usage(name: 'Helianthus', rank: 'SPECIES')
test['results'].map{ |t| t['rank'] }.tally
=> {"GENUS"=>64, nil=>2, "SPECIES"=>2}

test = species.name_usage(name: 'Helianthus')
test['results'].length
=> 68
```

**shortname**

The comments in the code say: A short name..need more info on this?

I'm not seeing it documented in the Species API at all. It's referenced in terms of the `/species/root/{uuid|shortname}` route, but that is not the root being used by this `name_usage` method.

**Comment by sckott** [comment]
- `key`: makes sense to remove if `data` is removed, but see below
- `uuid`: sounds good to remove
- `data`, I think we need to rewrite the `name_usage` method. `data` here refers to the url route here https://www.gbif.org/developer/species#nameUsages e.g., `/species/{int}` vs. `/species/{int}/verbatim`. We can support those various requests by modifying the url route by doing e.g,  `/species/5231190/distributions` and `/species/5231190/descriptions`. The taxon key `5231190` would be specified using the `key` parameter
- `rank`: sounds good to remove
- `shortname`: sounds good to remove

thoughts?
